### PR TITLE
Update gulpfile for Gulp 4.x

### PR DESCRIPTION
**Pull request by ogdendavis**
update to terser for es6 support
change default task to use series
rename AUTOPREFIXER_BROWSERS per runtime warning

### CODE REVIEW

**Review by ConfidenceYobo — CHANGES_REQUESTED** [review]
gulp-terser should be added to package.json and also gulp version in package.json should be changed to '^4.0.0'

**Comment by ogdendavis** [comment]
Good point -- I had updated packages in the project I used this in, but forgotten to update the package.json in this pull request. Fixed, now.

**Review by ConfidenceYobo — APPROVED** [review]
👍👍👍 great one, I suggest this or gets considered

**Comment by ogdendavis** [comment]
Closing because it's so darn old

**Pull request closed without merging**
